font_size 13

background_opacity 0.7
window_padding_width 0 15 0 15

disable_ligatures never

# BEGIN_KITTY_THEME
# Rosé Pine
include current-theme.conf
# END_KITTY_THEME


# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      family="JetBrainsMono Nerd Font"
bold_italic_font family="JetBrainsMono Nerd Font"
# END_KITTY_FONTS

