[[block]]
block = "focused_window"
format = " $title.str(max_w:50) |"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = " $icon $available "

[[block]]
block = "memory"
format = " $icon $mem_used_percents "

[[block]]
block = "cpu"
format = " $icon $utilization "

[[block]]
block = "temperature"
format = " $icon $max "
chip = "*-isa-*"
interval = 5

[[block]]
block = "net"
format = " $icon $ip "
missing_format = " No Network "

[[block]]
block = "sound"
format = " $icon $volume "

[[block]]
block = "backlight"
format = " $icon $brightness "
missing_format = ""

[[block]]
block = "battery"
format = " $icon $percentage "
missing_format = ""

[[block]]
block = "time"
format = " $icon $timestamp.datetime(f:'%a %d %b %I:%M %p') "
interval = 60

[[block]]
block = "menu"
text = " ⏻ "

[[block.items]]
display = " Lock"
cmd = "loginctl lock-session"

[[block.items]]
display = "󰍃 Logout"
cmd = "i3-msg exit"

[[block.items]]
display = " Reboot"
cmd = "systemctl reboot"

[[block.items]]
display = " Shutdown"
cmd = "systemctl poweroff"
