icons_format = "{icon}"

[theme]
theme = "tomorrow-night"

[theme.overrides]
separator = " "

[icons]
icons = "awesome6"

[[block]]
block = "custom"
command = "echo '  '"
interval = "once"
[[block.click]]
button = "left"
cmd = "playerctl previous"
[block.theme_overrides]
separator = ""

[[block]]
block = "music"
format = " $icon  $combo.str(max_w:40) "
[[block.click]]
button = "left"
cmd = "playerctl play-pause"
[block.theme_overrides]
separator = ""

[[block]]
block = "custom"
command = "echo '  '"
interval = "once"
[[block.click]]
button = "left"
cmd = "playerctl next"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon  root: $available "

[[block]]
block = "memory"
format = " $icon  $mem_used_percents "
format_alt = " $icon_swap $swap_used_percents "
warning_mem = 70
critical_mem = 95

[[block]]
block = "cpu"
interval = 1
format = "  $icon $utilization"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "sound"
format = " $icon  $volume "
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "

[[block]]
block = "menu"
text = " ⏻  "

[[block.items]]
display = " Lock "
cmd = "loginctl lock-session"

[[block.items]]
display = "󰍃 Logout "
cmd = "i3-msg exit"

[[block.items]]
display = " Reboot "
cmd = "systemctl reboot"

[[block.items]]
display = " Shutdown "
cmd = "systemctl poweroff"
