# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# --- TOP LEVEL CONFIGS ---
add_newline = true
scan_timeout = 1000 # Increased to 1 second

[character]
success_symbol = '[➜](bold green)'

[package]
disabled = true
